name: CI

env:
  DEFAULT_BRANCH: 'refs/heads/feature/sprint'
  GRADLE_VERSION: '5.6.4'

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
  pull_request:

jobs:
  build:
    if: startsWith(github.head_ref, 'feature/sprint') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cleanup runs
        run: ./scripts/cancel_jobs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache gem dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/*Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install gem
        run: |
          gem install bundle
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ env.GRADLE_VERSION }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.GRADLE_VERSION }}-
      - name: Run Gradle to cache
        if: startsWith(github.ref, env.DEFAULT_BRANCH) == true
        run: ./gradlew clean

      - name: Run detekt
        if: github.event_name == 'pull_request'
        run: ./gradlew clean detekt

      #      - name: Run unitest
      #        if: github.event_name == 'pull_request'
      #        run: ./gradlew test jacocoTestReport
      #
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        if: github.event_name == 'pull_request'
        with:
          name: UnitTest-Artifact
          path: 'app/build/reports/'

      - name: Report github
        if: github.event_name == 'pull_request'
        run: bundle exec danger --danger_id=check_style --dangerfile=Dangerfile
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}