# This is a basic workflow to help you get started with Actions

name: detekt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  jobs:
    detekt:
      runs-on: ubuntu-latest

      steps:
        - name: "checkout"
          uses: actions/checkout@v2

        - name: "detekt"
          uses: natiginfo/action-detekt-all@1.20.0
          with:
            args: --failt-fast --config detekt.yml